backend:
  name: github
  repo: skifte/limisvingen

# https://www.netlifycms.org/docs/configuration-options/
publish_mode: editorial_workflow #Lager ny branch og pull request i stedet for commit og push til master (på save draft).
site_url: https://limisvingen.no
locale: 'no'

media_folder: static/images
public_folder: "/images" #hvor bilder havner i bygd site. Default er /media_folder

collections:
  - name: artikkel
    label: Artikkel
    folder: content/artikler
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: referat
    label: Referat
    folder: content/referater
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }