backend:
  name: github
  repo: skifte/limisvingen
  
media_folder: static/assets

collections:
  - name: artikkel
    label: Artikkel
    folder: content/artikler
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: referat
    label: Referat
    folder: content/referater
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }